
security:
  basic:
    enable: false

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgresdb
    username: postgres_user
    password: postgres_password


