version: '3'
services:
  products:
    restart: always
    build:
      context: ../
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=postgres:5432
      - DATABASE_NAME=postgresdb
      - DATABASE_USERNAME=postgres_user
      - DATABASE_PASSWORD=postgres_password
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - PGDATA=/var/lib/pgsql_docker/data
    ports:
      - "5432:5432"